# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kstask',
            name='resolver_method',
            field=models.CharField(choices=[('greedy_heuristic', 'Greedy Heuristic'), ('dynamic', 'Dynamic Programming'), ('branch_bound', 'Branch & Bound')], default='greedy_heuristic', max_length=50, verbose_name='Resolver method'),
        ),
    ]
